name: looking
favicon: null
layout_spectrum: 0.858904741005972
typography_spectrum: 0.2672538503538817
title: looking
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6173456576652825
  lightness: 0.7153148546349257
  saturation: 0.05613245093263686
  rhythmicContrast: 0.07332103955559433
purpose: []
