name: looking
favicon: null
layout_spectrum: 0
typography_spectrum: 0.30613
title: looking
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#3a3a3a'
    - '#696969'
    - '#a4a4a4'
    - '#d2d2d2'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
